### ISSUE TITLE
Can u port to linux?

### ISSUE THREAD

**Issue by vssasks** [0EVSG/snd_hdsp#1]
Stock alsa driver blocks buffers smaller than 64. What about this one?

**Comment by 0EVSG** [comment]
There's no restriction, you can set the buffer to 32 samples, and I'm sure I did test it when I wrote the driver. That said, it doesn't work anymore in my current setup, maybe because of the firmware update I did in the meantime.

Porting the FreeBSD driver code to linux is not possible, this would have to be resolved in the linux driver. According to the comments there, 32 samples buffer size is not possible with RME HDSP cards, then again the windows driver seems to support it...

Sorry, can't help you with that.

**Comment by vssasks** [comment]
Nevermind, i  posted the same on rme forum and no one helped. I recompiled ko with editing ko code to support 32 but with new ko playback did not work... tbough i could select buffer 32 in reaper.
